export const lightGreyBlue = "#F9FAFD";
export const snow = "#F7FAFD";
export const white = "#FFFFFF";
export const veryDarkBlue= "#1C202B";
export const darkGreyBlue= "#5E6778";
export const blue = "#0A327B";
export const veryLightBlue = "#DDE7EE";
export const red = "#F65552";
export const greyBlue ="#939CAD";